[package]
name = "corky-charts"
version = "0.1.0"
edition = "2024"

[dependencies]
zmq = "0.10"
chrono = "0.4.26"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
plotters     = "0.3.4"
plotters-bitmap = "0.3"